version: '3.4'

services:

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./server-data/postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: admin
      POSTGRES_DB: db
    ports:
      - 5432:5432

  redis:
    image: "bitnami/redis:latest"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ./server-data/redis-data:/bitnami/redis/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
